# Base ngnix web server
nginx:
  enabled: true
  chart: "bitnami/nginx"
  service:
    type: ClusterIP
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      aviinfrasetting.ako.vmware.com/name: "dataclass-medium"
    hostname: nginx-e645h6-test.apps.emerald.devops.gov.bc.ca
  version: "15.11.0"
  image:
    pullPolicy: Always
  podLabels:
    environment: test
    env: test
    owner: "ntt-lea"
    project: "abcd"
    DataClass: "Medium"
  commonLabels:
    environment: test
    env: test
    owner: "ntt-lea"
    project: "abcd"
    DataClass: "Medium"
    app.kubernetes.io/part-of: "abcd"
  replicaCount: 1
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      memory: 100Mi
      cpu: 20m

# Normal Postgres DB instance
postgresql:
  enabled: false
  image:
    pullPolicy: Always
  commonLabels:
    environment: test
    env: test
    owner: "ntt-lea"
    project: "abcd"
    DataClass: "Medium"
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    networkPolicy:
      enabled: false
    labels:
      environment: test
      env: test
      owner: "ntt-lea"
      project: "abcd"
      DataClass: "Medium"
    podLabels:
      environment: test
      env: test
      owner: "ntt-lea"
      project: "abcd"
      DataClass: "Medium"
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        memory: 256Mi
        cpu: 100m

#  this will create postgres database with HA and
postgresql-ha:
  enabled: true
  backup:
    enabled: true
    image:
      pullPolicy: Always
    cronjob:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
      schedule: "*/5 * * * *"
      resources:
        limits:
          cpu: 50m
          memory: 256Mi
        requests:
          memory: 100Mi
          cpu: 20m
      storage:
        size: 256Mi

  postgresql:
    image:
      pullPolicy: Always
    podSecurityContext:
      enabled: false
    persistence:
      size: 256Mi
    replicaCount: 2
    containerSecurityContext:
      enabled: false
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        memory: 256Mi
        cpu: 100m
  pgdumpall:
    podSecurityContext:
      enabled: false
    persistence:
      size: 256Mi
    containerSecurityContext:
      enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 1Gi
      requests:
        memory: 256Mi
        cpu: 20m

  pgpool:
    containerSecurityContext:
      enabled: false
    image:
      pullPolicy: Always
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        memory: 100Mi
        cpu: 20m

  commonLabels:
    environment: test
    env: test
    owner: "ntt-lea"
    project: "abcd"
    DataClass: "Medium"
    app.kubernetes.io/part-of: "abcd"

telnet:
  enabled: true
  goldService: "sso-e27db1-dev.apps.gold.devops.gov.bc.ca" # testing connectivity from emerald to a service GOLD using telnet
  goldPort: 80
  diamSSO: test.common-sso.justice.gov.bc.ca # testing outbound to DIAM Common-SSO
  diamPort: 80
  diamEgressIP: 142.34.51.102/32
  publicService: "https://docker.io" # testing connectivity from emerald to internet via web proxy using curl
  gitHubUrl: "https://github.com/bcgov/JAG-GITOPS-TEMPLATE.git" # test connectivity outbound to github via git clone
  commonLabels:
    environment: test
    env: test
    owner: "ntt-lea"
    project: "abcd"
    DataClass: "Medium"
    app.kubernetes.io/part-of: "abcd"
