project: e645h6
kind: Application
metadata:
  name: lea-api-gitops-test
spec:
  destination:
    name: ''
    namespace: e645h6-test
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/gitops
    repoURL: 'git@github.com:bcgov-c/tenant-gitops-e645h6.git'
    targetRevision: test
    helm:
      valueFiles:
        - $values/deploy/test_values.yaml
  project: e645h6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true