project: e645h6
kind: Application
metadata:
  name: lea-api-gitops-prod
spec:
  destination:
    name: ''
    namespace: e645h6-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/gitops
    repoURL: 'git@github.com:bcgov-c/tenant-gitops-e645h6.git'
    targetRevision: main
    helm:
      valueFiles:
        - $values/deploy/prod_values.yaml
  project: e645h6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true